language: python

addons:
  apt:
    packages:
      - pandoc

python:
  - '3.7'
env:
  - TARGET=docs
  - TARGET=check-format
  - TARGET=check-types
  - TARGET=check-style
  - TARGET=test
jobs:
  include:
    - python: '3.6'
      env: TARGET=test
    - python: '3.8'
      env: TARGET=test

services:
  - docker

before_install:
  - docker run --rm -itd -p 5555:5555 rigetti/quilc -R
  - docker run --rm -itd -p 5000:5000 rigetti/qvm -S

install:
  - make install
  - make requirements

script:
  - make $TARGET
